trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildDir: 'dist'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npx pug src/pug --out $(buildDir)
  displayName: 'Compile Pug to HTML'

- script: npx sass src/scss:$(buildDir)/css
  displayName: 'Compile SCSS to CSS'

- script: |
    cp -r src/assets $(buildDir)/assets
    cp -r src/js $(buildDir)/js
  displayName: 'Copy Assets and JS'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'lba-vm'  # <-- Use your service connection name here
    sourceFolder: '$(Build.SourcesDirectory)/$(buildDir)'
    contents: '**'
    targetFolder: '/var/www/html/'  # <-- Change to your VM’s web root path
    cleanTargetFolder: true
    overwrite: true
  displayName: 'Deploy to My VM via SSH'

