trigger:
- master  # or your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Build App'

- script: |
    echo "Code ready for deployment"
  displayName: 'End CI Step'
